# Generated by Django 2.2.5 on 2020-01-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('last_night_sleep_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_warmup', models.BooleanField(default=False)),
                ('reps', models.IntegerField(null=True)),
                ('time_length', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_logger.Excercise')),
            ],
        ),
    ]
