# Generated by Django 2.2.5 on 2020-01-09 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_logger', '0002_excercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeasurements',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
