# Generated by Django 2.2.5 on 2020-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_logger', '0004_update_excercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
