# Generated by Django 2.2.5 on 2020-01-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_logger', '0006_auto_20200111_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeasurements',
            name='last_night_sleep_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailymeasurements',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
