# Generated by Django 2.2.5 on 2020-01-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_logger', '0010_food_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='default_quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
