# Generated by Django 2.2.5 on 2020-01-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_logger', '0011_food_default_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlanState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('state', models.TextField()),
            ],
        ),
    ]
